## dvc.yaml
stages:
  prepare_text_data:
    cmd: python src/preprocessing.py --type text
    deps:
      - src/preprocessing.py
      - data/raw
    outs:
      - data/processed/text

  prepare_data:
    cmd: python src/data_loader.py
    deps:
      - src/data_loader.py
      - data/raw
    outs:
      - data/processed/fusion

  train_text_model:
    cmd: python src/train.py --model text
    deps:
      - src/train.py
      - src/data_loader.py
      - data/processed
    outs:
      - models

  train_image_model:
    cmd: python src/train.py --model image
    deps:
      - src/train.py
      - src/data_loader.py
      - data/raw
    outs:
      - models

  train_fusion_model:
    cmd: python src/fusion_model.py --model fusion
    deps:
      - src/fusion_model.py
      - models
      - models
      - data/raw
      - data/processed
      - src/data_loader.py
    outs:
      - models
